codeit-FE15-4U/4U

src/api/axios.js
axios 기본 baseUrl 설정
> axios.js 파일 생성
- axios baseURL 설정
---
- Close # 2
---
(이미지 첨부)
---
=> ✨ axios.js 생성

src/api/subjects.js
- subject와 관련된 api 를 만들 subjects.js파일과 대상 질문 목록 조회를 할 getQuestionList함수를 만들었습니다. 파라미터 값으로 객체로 subjectId, limit, offset을 보내주면 subjectId에 맞는 질문 리스트를 받습니다.
- 아직 질문 데이터가 없어서 받아온 데이터를 확인 해 보진 못했지만 원하는 경로로 요청하는 것은 확인 했습니다.
- 처음에 question/id 에 get을 하는거(questionId를 보내면 질문 상세를 보내준다.)와 헷갈려서 api를 이해하느라 시간이 오래 걸렸습니다.
---
- Close # 8
---
(이미지 첨부)
---
=> ✨ 대상 질문 목록 조회 기능

src/App.css
- 테일윈드 기본 설정에 반응형 단위를 추가했습니다.
- 기존 반응형 디자인을 할 때 md:m-20 이런식으로 사용했을텐데 tablet:, pc: 이런식으로 반응형 디자인 하시면 됩니다.
- 테스트 완료했습니다.
- tablet 단위(768px 기존 md와 동일) 추가, pc 단위(1200px) 추가했습니다.
---
- Close #19
---
(이미지 첨부)
---
=> feat/19-테일윈드 반응형 단위 추가

src/components/QuestionLayout.jsx
> 질문 레이아웃에서 name, questionCount, imageSource를 받아와야 하는데 name만 받아왔습니다.
---
- Close #42
---
(이미지 첨부)
---
=> 🐛 location으로 받아오는 값 수정

src/components/Button.jsx, src/pages/ListPage.jsx
- button hover 했을 때 border 크기가 늘어나는 것 수정(border -> outline으로 변경)
---
- Close #40
---
(이미지 첨부)
---
=> 🐛 button hover 했을 때 border 크기가 늘어나는 것 수정

src/components/QuestionBox.jsx
- px값이 디자인과 달라 수정했습니다.
- 메시지 아이콘을 svg로 받아왔습니다.
---
- Close #50 
---
(이미지 첨부)
---
=> Feat/50 질문박스 수정

src/components/InputTextarea.jsx
- 장문의 글을 작성하는 Input Textarea 공통 컴포넌트를 만들었습니다.
- props
- name: id와 name 설정
- className: 추가적인 tailwind 속성 및 class 이름
- placeholder
- value: 초기값
- setValue: 상위의 state의 값을 동기화시키기 위한 set 함수
---
- Close #48 
---
---
=> [Feat] Input Textarea 구현

src/App.jsx, src/components/QuestionLayout.jsx, src/pages/QuestionPage.jsx
- 질문 페이지를 생성합니다.
- 질문이 0개일 경우 아직 질문이 없습니다 텍스트를 보여줍니다
---
- Close #49
---
(이미지 첨부)
---
=> Feat/49 질문페이지 구현

src/api/subjects.js
- 질문에 답변을 게시하는 postAnswer 함수 구현
- 답변을 수정하는 patchAnswer 함수 구현
- Close #56
=> [Feat] postAnswer patchAnswer 함수 추가

src/App.jsx, src/components/QuestionLayout.jsx, src/pages/AnswerPage.jsx
- 답변 페이지를 만들었습니다.
- 삭제 버튼은 컴포넌트가 만들어지면 교체가 필요합니다.
---
- Close #52
---
(이미지 첨부)
---
=> Feat/52 답변페이지 구현

src/components/Button.jsx
- 예시: round 버튼 패딩, 길이값 제거
---
- Close #78
---
(이미지 첨부)
---
=> Feat/78 round 버튼 패딩, 길이값 제거

src/api/subjects.js, src/components/Button.jsx, src/components/QuestionLayout.jsx, src/pages/AnswerPage.jsx
- 답변 페이지의 삭제 버튼 구현
- 요구사항에는 없지만 다른 기능을 모두 구현한 후에 추가적으로 삭제할건지 확인하는 기능을 추가하면 좋을 거 같습니다.
---
- Close #74
---
(이미지 첨부)
---
=>  feat/74 답변 페이지 삭제 기능 구현

src/components/QuestionButton.jsx, src/components/QuestionModal.jsx, src/pages/QuestionPage.jsx
> 질문작성하기 버튼을 만들었습니다 -> 임시 모달창을 만들어 연결했습니다.
- 버튼 작동을 위해 모달창을 임시로 만들었습니다.
- 버튼은 Floating 버튼으로 fix로 화면에 고정됩니다.
- 모바일일땐 질문작성/ 타블렛이상일땐 질문작성하기
- 기본요구사항
“질문 작성하기” 버튼을 클릭하면 “질문을 작성하세요”  모달이 뜹니다.
- 모달
모달의 X 버튼, 모달 내용을 벗어난 부분을 클릭하면 모달을 닫습니다.
모달에 질문 내용이 없는 경우 “질문 보내기” 버튼은  비활성화 상태입니다. 질문 내용이 있는 경우 활성화 됩니다.
(임시)모달창이므로 기능은 구현되지 않았습니다.
*원래 모달창 기능작업하시는 분께서는 삭제하고 작업해주셔도 무관합니다.
---
- Close #72 
---
(이미지 첨부)
---
=> Feat/72 질문 작성 버튼 디자인

src/api/subjects.js, src/pages/ListPage.jsx
- Listpage에 정렬기능 추가
- dropdown 클릭시 옵션에 따라 정렬되도록 click에 함수 전달
---
- Close #60
---
---
=> Feat/Listpage에 정렬기능 추가

src/api/subjects.js
- postAnswer patchAnswer API 함수의 반환값을 response에서 response.data로 변경
- PR 한다면 rebase로 할 예정입니다
- Close #82
=> [Fix] postAnswer patchAnswer 반환값 변경

src/pages/AnswerPage.jsx, src/pages/ListPage.jsx
- 로고 클릭 시 메인 페이지로 이동
- 질문하러 가기 클릭 시 localstorage에 id가 없으면 메인페이지로 이동
- 질문하러 가기 클릭 시 localstorage에 id가 있으면 answerPage로 이동
- answerPage로 이동할 때 user 데이터 함께 전달
---
- Close #69
---
데이터 전송 예시
---
=> [Feat] listpage 버튼 기능 추가

src/components/Badge.jsx
- completed prop (Boolean) 값에 따라 보여주는 형태가 바뀌는 Badge 컴포넌트 구현
- Close #45
=> Feat/45 Badge 컴포넌트 구현

src/components/DropdownTrigger.jsx, src/components/UserCard.jsx, src/pages/ListPage.jsx
- listPage icon 수정
- Button icon 수정
- Dropdown icon 수정
---
- Close #85
---
(이미지 첨부)
---
=> [Feat]listpage 관련 icon 일괄 수정

src/components/InputTextarea.jsx
- setState 함수 대신 ref로 수정하여 불필요 리렌더링을 줄임
- value > defaultValue로 수정
- commit이 하나 뿐이라 merge 시 rebase로 병합할 것
- Close #87
=> [feat] InputTextarea 로직 수정

src/components/Toast.jsx
- 토스트 컴포넌트를 생성했습니다.
---
- Close #70
---
(이미지 첨부)
---
=> Feat/70 토스트 컴포넌트 구현

src/api/answers.js, src/api/questions.js, src/api/subjects.js, src/components/QuestionLayout.jsx, src/pages/ListPage.jsx
- api 를 분리했습니다.
- 바뀐 부분이 많이 없어서 바뀐 부분도 수정했습니다.
---
- Close #92
---
(이미지 첨부)
---
=> Feat/92 api함수 분리

src/components/FacebookShareButton.jsx, src/components/QuestionLayout.jsx
- 페이스북 공유 버튼을 만들었습니다.
- 로컬호스트 주소는 공유가 안된다고 해서 네이버 주소를 넣어서 테스트 해보니 잘 되는것을 확인 했습니다.
---
- Close #65
---
(이미지 첨부)
---
=> Feat/65 페이스북 공유버튼 구현

src/components/Reaction.jsx
> ui생성
- 
- Close #102 
---
---
=> ✨ 리액션 좋아요 및 싫어요 버튼 구현

src/App.jsx, src/components/QuestionContainer.jsx, src/components/QuestionLayout.jsx, src/pages/AnswerPage.jsx, src/pages/QuestionPage.jsx
- 질문 레이아웃에 있던 기능들을 페이지로 옮기고 이름을 컨테이너로 바꾸었습니다.
- 라우팅도 수정하였습니다.
---
- Close #97
---
(이미지 첨부)
---
=> Feat/97 질문답변 구조 개선

src/api/answers.js, src/api/questions.js, src/api/subjects.js
- api에서 try문을 제거했습니다.
---
- Close #110
---
(이미지 첨부)
---
=> feat/110 try문 제거

src/components/FeedCard.jsx
- FeedCard에 Badge 컴포넌트를 추가하였습니다.
- 가능하다면 rebase로 merge할 예정입니다.
- Close #89
=> [Feat] FeedCard에 Badge 추가

src/components/QuestionContainer.jsx, src/components/QuestionList.jsx, src/components/SkeletonFeedCard.jsx, src/components/SkeletonSubject.jsx, src/pages/AnswerPage.jsx, src/pages/QuestionPage.jsx
- 질문/답변 페이지 스켈레톤 UI를 구현했습니다.
- 질문 리스트 컴포넌트를 만들어 분리했습니다.
---
- Close #117
---
(이미지 첨부)
---
=> Feat/117 질문답변 페이지 스켈레톤UI

src/pages/ListPage.jsx, src/pages/MainPage.jsx
- mainPage에서 localstorage에 저장하는 방식 변경
- listPage에서는 selectedSubject 하나만 불러오는 것으로 임시 설정
---
- Close #115
---
mainPage에서 저장 후 listPage로 넘겨주는 방식
listPage에서 답변하러가기 클릭 시 넘겨주는 방식
(이후 리스트 중에서 선택하는 것으로 변경 예정)
---
=> [Feat] localsotrage에 id 값 리스트로 저장

src/components/FeedCardAnswerInput.jsx, src/components/InputTextarea.jsx, src/components/QuestionModal.jsx
- 기존의 `textarea` 요소를 `InputTextarea` component로 수정하였습니다.
- 따라서 message가 state에서 ref가 되었습니다.
- `InputTextarea`에 `onChange` prop을 추가하였습니다.
- 위 변화로 `FeedCardAnswerInput`의 `handleChange` event handler 역시 위치가 바뀌었습니다.
- `Button`의 `disabled` 속성으로 버튼을 연타되는 것을 방지하였습니다.
- Close #124
=> Feat/124 QuestionModal에 inputTextarea 컴포넌트 추가 및 중복 Request 방지

src/components/Pagenation.jsx, src/components/UserCard.jsx, src/components/UserList.jsx
- userCard 내부 요소 tablet 이상일 때 커지도록 수정
- userList 에서의 gap tablet 이상일 때 값 변경
- pagenation에서 padding tablet 이상일 때 값 변경
---
- Close #137
---
(이미지 첨부)
---
=> [Feat] usercard 내부 반응형 구현

src/components/FeedCard.jsx, src/components/Reaction.jsx
- FeedCard에서 Reaction 부분의 디자인을 적용했습니다
- Close #7
=> [Feat] FeedCard Reaction 부분 디자인

src/components/DropdownMenu.jsx, src/components/DropdownTrigger.jsx, src/components/FeedCard.jsx, src/pages/ListPage.jsx
- dropdown에 cursor-pointer 설정
- dropdown 외부에서 className 정할 수 있도록 속성 추가
---
- Close #133
---
(이미지 첨부)
---
=> [Bug] dropdown UI hover 문제

src/App.css, src/components/Toast.jsx, src/components/UrlShareButton.jsx
- 토스트 애니메이션을 만들었습니다.
- app.css에 토스트가 생길 때 사라질 때 애니메이션을 추가했습니다.
- Toast 컴포넌트에 isVisble상태를 만들어서 생길 때와 사라질 때 애니메이션을 다르게 넣어주었습니다.
- 애니메이션을 0.5초로 해 주어서 0.5초 애니메이션이 나온 뒤 토스트 컴포넌트가 없어지게 하려 했지만 0.5초로 하면 시간이 살짝 안맞는 문제가 있어서 0.4초 뒤 없어지게 했습니다.
---
- Close #142
---
(이미지 첨부)
https://github.com/user-attachments/assets/cb44620a-0046-4204-aa37-1b81d5f41371
---
=> Feat/142-토스트 애니메이션

src/components/SkeletonUserCard.jsx, src/components/UserCard.jsx, src/components/UserList.jsx, src/pages/ListPage.jsx
- SkeletonUserCard를 만들어서 적용하였습니다
- UserList에 itemsPerPage prop을 추가하고 구조를 변경하였습니다
- Close #131
=> Feat/131 SkeletonUserCard 구현

src/components/DeleteButton.jsx, src/components/DeleteModal.jsx, src/pages/AnswerPage.jsx
- 삭제버튼을 컴포넌트로 분리했습니다.
- 삭제버튼을 누르면 모달창이 나와 삭제 할건지 확인합니다.
---
- Close #144
---
(이미지 첨부)
---
=> Feat/144 삭제 확인하는 기능

src/pages/AnswerPage.jsx, src/pages/QuestionPage.jsx
- 로컬의 id와 비교해서 자동으로 질문/답변페이지로 이동합니다
---
- Close #101
---
(이미지 첨부)
---
=> Feat/101 로컬id와 비교하여 페이지 리다이렉트

vercel.json
- SPA 프로젝트를 배포한 뒤 동적으로 라우팅 접근시, (즉 라우트 이동 후 중간에 새로고침하거나, 하위 url(ex. moonshot/dashboard)로 접근했을 경우 vercel에서는 404 Not_Found 에러를 뱉습니다.
이를 해결하는 파일을 만듭니다.
---
- Close #157
---
(이미지 첨부)
---
=> Feat/157-vercel설정 추가

src/components/shareButton/KakaoShareButton.jsx
- 이미지나 맨 아래를 누르면 메인 페이지로 이동하고 자세히 보기를 누르면 공유한 페이지로 이동합니다.
- 변경을 원하시거나 개선사항 있으면 댓글 달아주세요
---
- Close #159
---
(이미지 첨부)
---
=> Feat/159-카카오 공유내용 수정

src/components/feedCard/FeedCard.jsx
- whitespace-pre-wrap 속성 추가를 통해 줄 바꿈과 여러 공백을 인식하게 했습니다.
---
- Close #176
---
(이미지 첨부)
---
=> Bug/176-완료된 답변에서 줄바꿈 인식 못함

src/components/InputField.jsx
- 모바일 사이즈에서 너비 고정값으로 변경
---
- Close #174
---
(이미지 첨부)
---
=> [Bug] 메인페이지 inputField 사이즈

src/components/feedCard/FeedCard.jsx, src/components/feedCard/FeedCardDropdown.jsx, src/components/question/QuestionList.jsx, src/pages/AnswerPage.jsx
- setQuestionCount를 내려주어 질문을 삭제할 때 갯수도 줄이게 했습니다.
- 질문을 삭제할 때 삭제한 질문을 담는 리스트를 만들어 li를 렌더링 할 때 리스트에 있다면 렌더링을 안하게 해 주었습니다.
---
- Close #149
---
(이미지 첨부)
---
=> Bug/149 질문을 삭제했을 때 질문 개수, 리스트 수정 필요

src/components/feedCard/FeedCardQuestion.jsx
- FeedCard의 질문 부분에서도 줄바꿈이 적용되도록 변경했습니다.
- Close #178
=> fix/178 FeedCard 질문 부분 줄바꿈 인식되도록 수정

src/pages/ListPage.jsx
- 8개 -> 6개로 바뀌는 지점 변경
- userCard 반응형 추가할 때 gap을 재설정하면서 오류가 생긴 것으로 확인
---
- Close #181
---
---
=> [Bug] 태블릿 사이즈 userCard 수 오류

src/components/InputField.jsx
- 길이를 체크해서 15자 이하일 때만 set
- 이러면 한글을 입력해도 15자 까지만 입력이 됩니다.
- 하지만 한글로 16자 이상 입력했을 때 보이는 글자는 없지만 백스페이스를 2번 해 주어야 15번째 글자가 지워집니다. 
---
- Close #180
---
(이미지 첨부)
---
=> bug/180-15자 초과

src/components/shareButton/KakaoShareButton.jsx
- 카카오톡 모바일 공유 url을 추가했습니다.
- 잘 되는거 같습니다!
---
- Close #193
---
(이미지 첨부)
---
=> bug/193-카카오톡 공유 내용

src/components/skeletonUi/SkeletonUserCard.jsx
- SkeletonUserCard가 tablet/PC 환경에서 크기가 맞지 않는 부분을 수정하였습니다.
- Close #198
=> fix/198 skeletonUserCard 크기 맞춤

src/components/InputTextarea.jsx, src/components/feedCard/FeedCardAnswerInput.jsx
- InputTextarea의 MaxLength props을 추가하였습니다.
- 답변의 최대 글자수를 10000자로 제한하였습니다.
- Close #197
=> Feat/197 답변 최대 글자수 제한
